routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CatalogueController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\TeamController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::get('/tu-van', [HomeController::class, 'advise'])->name('advise');
Route::any('/gioi-thieu', [HomeController::class, 'about'])->name('about');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::any('/lien-he', [HomeController::class, 'contact'])->name('contact');
Route::get('/san-pham/{alias}', [App\Http\Controllers\ProductController::class, 'detail'])->name('product.detail');
Route::get('/danh-muc/{alias}', [App\Http\Controllers\ProductController::class, 'catalogue'])->name('product.catalogue');
Route::get('/tin-tuc/', [App\Http\Controllers\PostController::class, 'index'])->name('post.list');
Route::get('/danh-muc-tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'category'])->name('post.category');
Route::get('/tim-kiem-tin-tuc', [App\Http\Controllers\PostController::class, 'search'])->name('post.search');
Route::get('/tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'detail'])->name('post.detail');

Route::middleware(['auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('', [DashboardController::class, 'index'])->name('index');
    Route::get('logout', [DashboardController::class, 'logout'])->name('logout');
    Route::any('profile', [DashboardController::class, 'profile'])->name('profile');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //User
    Route::resource('user', UserController::class);
    //Slide
    Route::resource('slide', SlideController::class);
    //Menu
    Route::resource('menu', MenuController::class);
    //Order
    Route::resource('order', OrderController::class);
    //Category
    Route::resource('category', CategoryController::class);
    //Catalogue
    Route::resource('catalogue', CatalogueController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    //Post
    Route::resource('post', PostController::class);
    //Message
    Route::resource('message', MessageController::class);
    //Testimonial
    Route::resource('testimonial', TestimonialController::class);
    //Team 
    Route::resource('team', TeamController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    Route::prefix('post')->name('post.')->group(function () {
        Route::post('category', [PostController::class, 'category'])->name('category');
    });
    //Product
    Route::resource('product', ProductController::class);
    Route::prefix('product')->name('product.')->group(function () {
        Route::post('category', [ProductController::class, 'category'])->name('category');
    });
    //Setting
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('', [SettingController::class, 'index'])->name('index');
        Route::post('', [SettingController::class, 'update'])->name('update');
    });
});

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Config;
use DB;

class SettingController extends Controller
{
    public function index()
    {
        $config = Config::all()->keyBy('name');
        return view('admin.setting.index',compact('config'));
    }
    public function update(Request $request)
    {
        DB::beginTransaction();
        try {

            if ($request->image) {
                Config::where('name','logo')->update(['value'=>$request->image]);
            }
            if ($request->hotline) {
                Config::where('name','hotline')->update(['value'=>$request->hotline]);
            }
            if ($request->address) {
                Config::where('name','address')->update(['value'=>$request->address]);
            }
            if ($request->email) {
                Config::where('name','email')->update(['value'=>$request->email]);
            }
            if ($request->image) {
                Config::where('name','about_title')->update(['value'=>$request->about_title]);
            }
            if ($request->hotline) {
                Config::where('name','about_content')->update(['value'=>$request->about_content]);
            }
            if ($request->address) {
                Config::where('name','about_image')->update(['value'=>$request->about_image]);
            }
            if ($request->email) {
                Config::where('name','about_video')->update(['value'=>$request->about_video]);
            }
            if ($request->image) {
                Config::where('name','contact_title')->update(['value'=>$request->contact_title]);
            }
            if ($request->hotline) {
                Config::where('name','facebook')->update(['value'=>$request->facebook]);
            }
            if ($request->address) {
                Config::where('name','instagram')->update(['value'=>$request->instagram]);
            }
            if ($request->email) {
                Config::where('name','youtube')->update(['value'=>$request->youtube]);
            }
            DB::commit();
            return redirect()->route('admin.setting.index')->with('message', 'Cập nhật thành công');
        }catch(Exception $ex) {
            DB::rollback();
            return back()->withInput();
        }
    }
}

resources/views/admin/setting/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-body">
            @include('admin.partials.message')
            <form action="{{route('admin.setting.update')}}" method="POST">
                @csrf
                <div class="form-group">
                    <label class="font-weight-semibold">Logo </label>
                    <input type="file" class="form-control-file" data-key="image" data-fouc>
                    @if(old('image'))
                    <input type="hidden" name="image" value="{{old('image')}}" id="image">
                    <img class="mt-2" id="image_preview" height="100" src="{{old('image')}}"/>
                    @elseif (isset($config) && isset($config['logo']))
                    <input type="hidden" name="image" value="{{$config['logo']->value}}" id="image">
                    <img class="mt-2" id="image_preview" height="100" src="{{$config['logo']->value}}"/>
                    @else
                    <input type="hidden" name="image" value="" id="image">
                    <img class="mt-2" id="image_preview" style="display:none;" height="100"/>
                    @endif
                </div>

                <div class="form-group">
                    <label class="font-weight-semibold">Email </label>
                    @if(old('email'))
                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}">
                    @elseif(isset($config['email']))
                    <input type="email" class="form-control" id="email" name="email" value="{{ $config['email']->value }}">
                    @else
                    <input type="email" class="form-control" id="email" name="email" value="">
                    @endif
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Địa chỉ </label>
                    @if(old('address'))
                    <input type="text" class="form-control" id="address" name="address" value="{{ old('address') }}">
                    @elseif(isset($config['address']))
                    <input type="text" class="form-control" id="address" name="address" value="{{ $config['address']->value }}">
                    @else
                    <input type="text" class="form-control" id="address" name="address" value="">
                    @endif
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Hotline </label>
                    @if(old('hotline'))
                    <input class="form-control" id="hotline" name="hotline" value="{{ old('hotline') }}">
                    @elseif(isset($config['hotline']))
                    <input class="form-control" id="hotline" name="hotline" value="{{ $config['hotline']->value }}">
                    @else
                    <input class="form-control" id="hotline" name="hotline" value="">
                    @endif
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Tiêu đề khối giới thiệu </label>
                    @if(old('about_title'))
                    <input class="form-control" id="about_title" name="about_title" value="{{ old('about_title') }}">
                    @elseif(isset($config['hotline']))
                    <input class="form-control" id="about_title" name="about_title" value="{{ $config['about_title']->value }}">
                    @else
                    <input class="form-control" id="about_title" name="about_title" value="">
                    @endif
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Nội dung khối giới thiệu </label>
                    @if(old('about_content'))
                    <textarea class="ckeditor form-control" id="about_content" name="about_content"> {{ old('about_content') }}</textarea>
                    @elseif(isset($config['hotline']))
                    <textarea class="ckeditor form-control" id="about_content" name="about_content"> {{ $config['about_content']->value }}</textarea>
                    @else
                    <input class="form-control" id="about_content" name="about_content" value="">
                    @endif
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Link ảnh khối giới thiệu</label>
                    <input type="text" class="form-control" id="about_image" name="about_image" value="{{ old('about_image')?? $config['about_image']->value }}">
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Link video khối giới thiệu (youtube)</label>
                    <input type="text" class="form-control" id="about_video" name="about_video" value="{{ old('about_video')?? $config['about_video']->value }}">
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Tiêu đề trang tư vấn </label>
                    <input type="text" class="form-control" id="contact_title" name="contact_title" value="{{ old('contact_title')?? $config['contact_title']->value }}">
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Facebook </label>
                    <input type="text" class="form-control" id="facebook" name="facebook" value="{{ old('facebook')?? $config['facebook']->value }}">
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Instagram </label>
                    <input type="text" class="form-control" id="instagram" name="instagram" value="{{ old('instagram')?? $config['instagram']->value }}">
                </div>
                <div class="form-group">
                    <label class="font-weight-semibold">Youtube </label>
                    <input type="text" class="form-control" id="youtube" name="youtube" value="{{ old('youtube')?? $config['youtube']->value }}">
                </div>
                <div class="text-right">
                    <button type="submit" class="btn btn-primary">Lưu <i class="icon-paperplane ml-2"></i></button>
                </div>
            </form>
        </div>
    </div>
<script>
    
</script>
@endsection