routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CatalogueController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\TeamController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::get('/tu-van', [HomeController::class, 'advise'])->name('advise');
Route::any('/gioi-thieu', [HomeController::class, 'about'])->name('about');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::any('/lien-he', [HomeController::class, 'contact'])->name('contact');
Route::get('/san-pham/{alias}', [App\Http\Controllers\ProductController::class, 'detail'])->name('product.detail');
Route::get('/danh-muc/{alias}', [App\Http\Controllers\ProductController::class, 'catalogue'])->name('product.catalogue');
Route::get('/tin-tuc/', [App\Http\Controllers\PostController::class, 'index'])->name('post.list');
Route::get('/danh-muc-tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'category'])->name('post.category');
Route::get('/tim-kiem-tin-tuc', [App\Http\Controllers\PostController::class, 'search'])->name('post.search');
Route::get('/tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'detail'])->name('post.detail');

Route::middleware(['auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('', [DashboardController::class, 'index'])->name('index');
    Route::get('logout', [DashboardController::class, 'logout'])->name('logout');
    Route::any('profile', [DashboardController::class, 'profile'])->name('profile');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //User
    Route::resource('user', UserController::class);
    //Slide
    Route::resource('slide', SlideController::class);
    //Menu
    Route::resource('menu', MenuController::class);
    //Order
    Route::resource('order', OrderController::class);
    //Category
    Route::resource('category', CategoryController::class);
    //Catalogue
    Route::resource('catalogue', CatalogueController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    //Post
    Route::resource('post', PostController::class);
    //Message
    Route::resource('message', MessageController::class);
    //Testimonial
    Route::resource('testimonial', TestimonialController::class);
    //Team 
    Route::resource('team', TeamController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    Route::prefix('post')->name('post.')->group(function () {
        Route::post('category', [PostController::class, 'category'])->name('category');
    });
    //Product
    Route::resource('product', ProductController::class);
    Route::prefix('product')->name('product.')->group(function () {
        Route::post('category', [ProductController::class, 'category'])->name('category');
    });
    //Setting
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('', [SettingController::class, 'index'])->name('index');
        Route::post('', [SettingController::class, 'update'])->name('update');
    });
});

resources/views/admin/partials/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy; 2022 <a href="#">Học viện ielts</a> by <a href="https://kalzen.com" target="_blank">Kalzen Media</a>
        </span>

      
    </div>
</div>

resources/views/admin/partials/message.blade.php
@if (session('message'))
    <div class="alert alert-success alert-styled-left alert-arrow-left alert-dismissible">
        <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
        {{ session('message') }}
    </div>
@endif

resources/views/admin/partials/navbar.blade.php
<!-- Main navbar -->
<div class="navbar navbar-expand-md navbar-dark bg-brand navbar-static">
    <div class="navbar-brand">
        <a href="/admin" class="d-inline-block">
            <img src="{{asset('hocvienielts/images/logo-white.png')}}" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>

        <span class="navbar-text ml-md-3">
            <span class="badge badge-mark border-orange-300 mr-2"></span>
            Xin chào, {{auth()->user()->name}}!
        </span>

        <ul class="navbar-nav ml-md-auto">
            <li class="nav-item">
                <a href="{{route('admin.logout')}}" class="navbar-nav-link">
                    <i class="icon-switch2"></i>
                    <span class="d-md-none ml-2">Thoát</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- /main navbar -->

resources/views/admin/partials/sidebar.blade.php
<!-- Main sidebar -->
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

    <!-- Sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        Navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->
    <!-- Sidebar content -->
    <div class="sidebar-content">

        <!-- User menu -->
        <div class="sidebar-user-material">
            <div class="sidebar-user-material-body">
                <div class="card-body text-center">
                    <a href="{{route('admin.profile')}}">
                        <img src="/global_assets/images/placeholders/placeholder.jpg" class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
                    </a>
                    <h6 class="mb-0 text-white text-shadow-dark">{{auth()->user()->name}}</h6>
                    <span class="font-size-sm text-white text-shadow-dark">{{auth()->user()->email}}</span>
                </div>
                <div class="sidebar-user-material-footer">
                    <a href="#user-nav" class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle" data-toggle="collapse"><span>Tài khoản</span></a>
                </div>
            </div>

            <div class="collapse" id="user-nav">
                <ul class="nav nav-sidebar">
                    <li class="nav-item">
                        <a href="{{route('admin.profile')}}" class="nav-link">
                            <i class="icon-user-plus"></i>
                            <span>Sửa thông tin</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('admin.logout')}}" class="nav-link">
                            <i class="icon-switch2"></i>
                            <span>Thoát</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /user menu -->
        <!-- Main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- Main -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
                <li class="nav-item">
                    <a href="{{route('admin.index')}}" class="nav-link">
                        <i class="icon-home4"></i>
                        <span>
                            Dashboard
                        </span>
                    </a>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="javascript:;" class="nav-link"><i class="icon-color-sampler"></i> <span>Giao diện</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Giao diện">
                        <li class="nav-item"><a href="javascript:;" class="nav-link active">Trang chủ</a></li>
                        <li class="nav-item"><a href="{{route('admin.slide.index')}}" class="nav-link">Slide</a></li>
                        <li class="nav-item"><a href="{{route('admin.menu.index')}}" class="nav-link">Menu</a></li>
                    </ul>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="javascript:;" class="nav-link"><i class="icon-pushpin"></i> <span>Bài viết</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Bài viết">
                        <li class="nav-item"><a href="{{route('admin.post.index')}}" class="nav-link">Tất cả bài viết</a></li>
                        <li class="nav-item"><a href="{{route('admin.post.create')}}" class="nav-link">Viết bài mới</a></li>
                        <li class="nav-item"><a href="{{route('admin.category.index')}}" class="nav-link">Chuyên mục</a></li>
                    </ul>
                </li>
               <!-- <li class="nav-item nav-item-submenu">
                    <a href="javascript:;" class="nav-link"><i class="icon-bag"></i> <span>Sản phẩm</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Sản phẩm">
                        <li class="nav-item"><a href="{{route('admin.product.index')}}" class="nav-link">Tất cả sản phẩm</a></li>
                        <li class="nav-item"><a href="{{route('admin.product.create')}}" class="nav-link">Thêm mới</a></li>
                        <li class="nav-item"><a href="{{route('admin.attribute.index')}}" class="nav-link">Thuộc tính</a></li>
                        <li class="nav-item"><a href="{{route('admin.order.index')}}" class="nav-link">Đơn hàng ({{$shared_orders_count}})</a></li>
                        <li class="nav-item"><a href="{{route('admin.catalogue.index')}}" class="nav-link">Danh mục</a></li>
                    </ul>
                </li> -->
                <li class="nav-item nav-item-submenu">
                    <a href="javascript:;" class="nav-link"><i class="icon-users"></i> <span>Thành viên</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Thành viên">
                        <li class="nav-item"><a href="{{route('admin.user.index')}}" class="nav-link">Tất cả người dùng</a></li>
                        <li class="nav-item"><a href="{{route('admin.user.create')}}" class="nav-link">Thêm mới</a></li>
                        <li class="nav-item"><a href="{{route('admin.profile')}}" class="nav-link">Hồ sơ</a></li>
                    </ul>
                </li>
                <li class="nav-item nav-item-submenu">
                    <a href="javascript:;" class="nav-link"><i class="icon-cog5"></i> <span>Cài đặt</span></a>

                    <ul class="nav nav-group-sub" data-submenu-title="Cài đặt">
                        <li class="nav-item"><a href="{{route('admin.setting.index')}}" class="nav-link">Tổng quan</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.team.index')}}" class="nav-link">
                        <i class="icon-users2"></i>
                        <span>
                            Đội ngũ
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.message.index')}}" class="nav-link">
                        <i class="icon-mailbox"></i>
                        <span>
                            Quản lý liên hệ
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{route('admin.testimonial.index')}}" class="nav-link">
                        <i class="icon-lasso2"></i>
                        <span>
                            Quản lý phản hồi
                        </span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->
</div>
<!-- /main sidebar -->