routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Admin\AttributeController;
use App\Http\Controllers\Admin\CatalogueController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\Admin\SlideController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\MessageController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Admin\TeamController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/logout', [HomeController::class, 'logout'])->name('logout');
Route::get('/tu-van', [HomeController::class, 'advise'])->name('advise');
Route::any('/gioi-thieu', [HomeController::class, 'about'])->name('about');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::any('/lien-he', [HomeController::class, 'contact'])->name('contact');
Route::get('/san-pham/{alias}', [App\Http\Controllers\ProductController::class, 'detail'])->name('product.detail');
Route::get('/danh-muc/{alias}', [App\Http\Controllers\ProductController::class, 'catalogue'])->name('product.catalogue');
Route::get('/tin-tuc/', [App\Http\Controllers\PostController::class, 'index'])->name('post.list');
Route::get('/danh-muc-tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'category'])->name('post.category');
Route::get('/tim-kiem-tin-tuc', [App\Http\Controllers\PostController::class, 'search'])->name('post.search');
Route::get('/tin-tuc/{alias}', [App\Http\Controllers\PostController::class, 'detail'])->name('post.detail');

Route::middleware(['auth'])->name('admin.')->prefix('admin')->group(function () {
    Route::get('', [DashboardController::class, 'index'])->name('index');
    Route::get('logout', [DashboardController::class, 'logout'])->name('logout');
    Route::any('profile', [DashboardController::class, 'profile'])->name('profile');
    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    //User
    Route::resource('user', UserController::class);
    //Slide
    Route::resource('slide', SlideController::class);
    //Menu
    Route::resource('menu', MenuController::class);
    //Order
    Route::resource('order', OrderController::class);
    //Category
    Route::resource('category', CategoryController::class);
    //Catalogue
    Route::resource('catalogue', CatalogueController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    //Post
    Route::resource('post', PostController::class);
    //Message
    Route::resource('message', MessageController::class);
    //Testimonial
    Route::resource('testimonial', TestimonialController::class);
    //Team 
    Route::resource('team', TeamController::class);
    //Attribute
    Route::resource('attribute', AttributeController::class);
    Route::prefix('post')->name('post.')->group(function () {
        Route::post('category', [PostController::class, 'category'])->name('category');
    });
    //Product
    Route::resource('product', ProductController::class);
    Route::prefix('product')->name('product.')->group(function () {
        Route::post('category', [ProductController::class, 'category'])->name('category');
    });
    //Setting
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('', [SettingController::class, 'index'])->name('index');
        Route::post('', [SettingController::class, 'update'])->name('update');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    const ROLE_USER = 1;
    const ROLE_ADMIN = 2;
    protected $guarded = [];
    protected $hidden = [
        'password',
        'remember_token',
    ];
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Http\Requests\UpdateUserRequest;
use App\Http\Controllers\Controller;
use App\Models\User;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $query = User::latest()->where('id','<>',auth()->user()->id);
        $records = $query->paginate();
        return view('admin.user.index',compact('records'));
    }
    
    public function create()
    {
        return view('admin.user.form');
    }
    
    public function store(CreateUserRequest $request)
    {
        try {
            $request->merge([
                'password' => bcrypt($request->password),
            ]);
            $user = User::create($request->only(['name','email','status']));
            return redirect()->route('admin.user.index')->with('message', 'Thêm mới thành công');
        } catch(Exception $ex) {
            return back()->withInput();
        }
    }
    
    public function show($id)
    {
        
    }
    
    public function edit($id)
    {
        $record = User::find($id);
        return view('admin.user.form',compact('record'));
    }
    
    public function update(UpdateUserRequest $request, $id)
    {
        try {
            $user = User::find($id);
            if ($request->password) {
                $request->merge([
                    'password' => bcrypt($request->password),
                ]);
                $user->update($request->only(['name','password','status']));
            } else {
                $user->update($request->only(['name','status']));
            }
            return redirect()->route('admin.user.index')->with('message', 'Cập nhật thành công');
        }catch(Exception $ex) {
            return back()->withInput();
        }
    }
    
    public function destroy($id)
    {
        User::find($id)->delete();
        return response()->json(['success'=>true,'message'=>'Xóa thành công']);
    }
    
}

resources/views/admin/user/form.blade.php
@extends('layouts.admin')
@section('content')
@if (isset($record))
<form method="POST" action="{{route('admin.user.update',$record->id)}}">
    @method('PUT')
@else
<form method="POST" action="{{route('admin.user.store')}}">
@endif
    @csrf
    <div class="content">
        <div class="d-flex align-items-start flex-column flex-md-row">
            <div class="w-100 overflow-auto order-2 order-md-1">
				<div class="card">
					<div class="card-body">
                        <div class="form-group">
                            <label class="font-weight-semibold">Tên <span class="required"></span></label>
                            <input type="text" class="form-control" required id="name" name="name" value="{{ old('name') ?: ($record->name ?? '') }}">
                            @error('name')
                            <label id="title-error" class="validation-invalid-label" for="name">{{$message}}</label>
                            @enderror
                        </div>
                        <div class="form-group">
                            <label class="font-weight-semibold">Email <span class="required"></span></label>
                            @if(isset($record))
                            <input type="email" class="form-control" disabled readonly value="{{ old('email') ?: ($record->email ?? '') }}">
                            @else
                            <input type="email" class="form-control" required id="email" name="email" value="{{ old('email') ?: ($record->email ?? '') }}">
                            @error('email')
                            <label id="email-error" class="validation-invalid-label" for="email">{{$message}}</label>
                            @endif
                            @enderror
                        </div>
                        <div class="text-right">
                            <button type="submit" class="btn btn-primary">Lưu <i class="icon-paperplane ml-2"></i></button>
                        </div>
                    </div>
				</div>
            </div>
            <div class="sidebar sidebar-light bg-transparent sidebar-component sidebar-component-right wmin-300 border-0 shadow-0 order-1 order-md-2 sidebar-expand-md">
                <div class="sidebar-content">
                    <div class="card">
                        <div class="card-body text-center">
                            <div class="form-check form-check-inline disabled">
                                <label class="form-check-label">
                                    <input type="radio" class="form-input-styled" {{isset($record) && $record->status == 1 ? 'checked' : ''}} name="status" value="1" checked data-fouc>
                                    Hoạt động
                                </label>
                            </div>

                            <div class="form-check form-check-inline disabled">
                                <label class="form-check-label">
                                    <input type="radio" class="form-input-styled" {{isset($record) && $record->status == 0 ? 'checked' : ''}} name="status" value="0" data-fouc>
                                    Khóa
                                </label>
                            </div>	
                        </div>
                    </div>
                    <div class="card">
                        <div class="card-body">
                            <div class="form-group">
                                <label class="font-weight-semibold">Mật khẩu</label>
                                <input type="password" class="form-control" name="password">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@php
use App\Models\User;
@endphp
@section('content')
    <div class="card">
        <div class="card-body">
            @include('admin.partials.message')
            <a class="btn mb-2 btn-success" href="{{route('admin.user.create')}}"><i class="icon-plus-circle2"></i> Thêm mới</a>
            @if(count($records))
            <div class="card card-table table-responsive shadow-0 mb-0">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Email</th>
                            <th>Tên</th>
                            <th>Quyền</th>
                            <th>Ngày tạo</th>
                            <th>Bài viết</th>
                            <th>Trạng thái</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($records as $record)
                        <tr>
                            <td>
                                <input type="checkbox" name="ids[]" value="{{$record->id}}" class="form-input-styled">
                            </td>
                            <td>
                                <a href="{{route('admin.user.edit', $record->id)}}">{{$record->email}}</a>
                            </td>
                            <td>
                                <a href="{{route('admin.user.edit', $record->id)}}">{{$record->name}}</a>
                            </td>
                            <td>
                                {{$record->role == User::ROLE_ADMIN ? 'Quản trị viên' : 'User'}}
                            </td>
                            <td class="text-center">
                                {{date('d/m/Y',strtotime($record->created_at))}}
                            </td>
                            <td class="text-center">
                                {{$record->posts()->count()}}
                            </td>
                            <td class="text-center">
                                @if($record->status)
                                <span class="badge bg-success">Hoạt động</span>
                                @else
                                <span class="badge bg-secondary">Khóa</span>
                                @endif
                            </td>
                            <td>
                                <a href="javascript:;" class="js-delete text-danger" data-key="{{$record->id}}" title="Xóa"><i class="icon-trash"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            <div class="mt-2">
                {{$records->links()}}
            </div>
            @else
            <div class="text-center p-5">
                <img src="/assets/img/no-data.png" alt="" srcset="">
                <p class="h4 mt-2 font-weight-semibold">Chưa có thành viên nào</p>
            </div>
            @endif
        </div>
    </div>
    <!-- /bordered card body table -->
<script>
    
    $('.js-delete').on('click', function() {
        let id = $(this).data('key')
        swal({
            title: 'Bạn chắc chắn muốn xóa?',
            text: "Thao tác sẽ không thể hoàn tác!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Xác nhận xóa!',
            cancelButtonText: 'Hủy',
            confirmButtonClass: 'btn btn-danger',
            cancelButtonClass: 'btn btn-default',
            buttonsStyling: false
        }).then(function (res) {
            if (res.value) {
                $.ajax({
                    url: '{{route('admin.user.destroy','idx')}}'.replace(/idx/, id),
                    method:'DELETE',data:{_token:'{{csrf_token()}}'},dataType:'json',
                    success:function(resp) {
                        toastr[resp.success ? 'success' : 'danger'](resp.message)
                        location.reload()
                    }
                })
            }
        }, function (dismiss) {});
    });
</script>
@endsection